"""Alembic environment for MedRec.

The URL always comes from backend/.env via app.core.config (same source
the app itself uses), so `alembic upgrade head` targets the real database.
Target metadata is the SQLAlchemy models — new schema changes should be
autogenerated (`alembic revision --autogenerate -m "..."`) and reviewed.
"""

from logging.config import fileConfig

from sqlalchemy import create_engine, pool

from alembic import context

from app.core.config import settings
from app.db.base import Base  # noqa: F401 — registers all models on metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# migrations.py (app startup) points this at the live, fallback-resolved
# engine URL. CLI runs fall back to settings.DATABASE_URL from backend/.env.
URL = config.get_main_option("sqlalchemy.url") or settings.DATABASE_URL
config.set_main_option("sqlalchemy.url", URL)
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(
        URL,
        poolclass=pool.NullPool,
        connect_args={"check_same_thread": False} if URL.startswith("sqlite") else {},
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
