import { Link } from 'react-router-dom'

const SECTIONS = [
  {
    title: '1. About MedRec',
    text: 'MedRec helps patients scan, store and organize medical reports and prescriptions, get plain-language AI summaries of their documents, and share their history with their doctors. Doctors can review the records of patients assigned to them.',
  },
  {
    title: '2. Privacy Policy',
    text: 'We collect only what the service needs: your account details (name, email, role, profile picture), your patient or doctor profile information, the documents you upload, and messages you send via Contact Us. Your records are visible only to you and to doctors you are assigned to — doctors cannot see unassigned patients. Login is handled through Firebase Authentication. We never sell your personal or medical data.',
  },
  {
    title: '3. Data storage & security',
    text: 'Uploaded files are stored on our secured servers (PostgreSQL + managed file storage) and served only to authenticated, authorized users. Passwords are never stored in readable form. AI summaries are generated by a self-hosted local model (Ollama) — your document text is not sent to third-party AI services. You may delete any document at any time, which also removes its AI summary.',
  },
  {
    title: '4. Terms of use',
    text: 'You must provide accurate registration information and keep your login credentials private. Upload only documents you own or are authorized to share. Do not misuse another patient\'s records or attempt to access unassigned data. Accounts that abuse the service may be suspended.',
  },
  {
    title: '5. Medical disclaimer',
    text: 'AI-generated summaries are informational only and are not a diagnosis, prescription, or medical advice. Always discuss your reports and any AI summary with a qualified doctor before making health decisions. In an emergency, contact local emergency services immediately.',
  },
  {
    title: '6. Contact & changes',
    text: 'Questions about this policy? Reach us anytime on the Contact Us page. We may update this policy as the service grows; the latest version will always be published here.',
  },
]

export default function Policy() {
  return (
    <div style={s.wrap}>
      <h1 style={s.title}>📜 Company Policy</h1>
      <p style={s.sub}>Privacy, terms of use and medical disclaimer for MedRec.</p>
      <div style={s.grid}>
        {SECTIONS.map((sec) => (
          <section key={sec.title} style={s.card}>
            <h3 style={s.h}>{sec.title}</h3>
            <p style={s.p}>{sec.text}</p>
          </section>
        ))}
      </div>
      <p><Link to="/contact">Contact Us</Link> if you have any questions about this policy.</p>
    </div>
  )
}

const s = {
  wrap: { width: '100%', padding: '26px 30px 40px' },
  title: { color: '#115e59', margin: '0 0 4px' },
  sub: { color: '#5f6f6a', margin: '0 0 16px' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(320px,1fr))', gap: 14 },
  card: { border: '1px solid #99f6e4', borderTop: '4px solid #0f766e', borderRadius: 12, padding: 18, background: '#fff' },
  h: { color: '#0f766e', margin: '0 0 8px' },
  p: { margin: 0, lineHeight: 1.7 },
}
