// Shared doctor specialization list (UK spellings as requested).
// Used by Register, Login (first-time doctor), DoctorProfile, DoctorDashboard.
export const SPECIALIZATIONS = [
  'General Physician',
  'General Surgery',
  'Orthopaedic',
  'Gynaecologist',
  'Paediatrician',
  'Cardiologist',
  'Dermatologist',
  'Neurologist',
  'Psychiatrist',
  'Ophthalmologist',
  'ENT Specialist',
  'Haematologist',
  'Endocrinologist',
  'Nephrologist',
  'Gastroenterologist',
  'Pulmonologist',
  'Oncologist',
  'Urologist',
  'Radiologist',
  'Anaesthetist',
  'Dentist',
  'Physiotherapist',
  'Ayurvedic',
  'Homoeopathic',
  'Other',
]
